# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZhouDaoSwift' do


pod 'SDWebImage', '~> 3.8.2'
pod 'CYLTabBarController', '~> 1.6.7'
pod 'IQKeyboardManagerSwift', '~> 4.0.7'
pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON', '~> 3.1.3'

#pod 'AFNetworking', '~> 3.1.0'

end

#target 'ZhouDaoSwiftTests' do
#
#end

#target 'ZhouDaoSwiftUITests' do
#
#end


