# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ZhouDaoSwift' do

end

target 'ZhouDaoSwiftTests' do

end

target 'ZhouDaoSwiftUITests' do

end

pod 'SDWebImage', '~> 3.8.2'
pod 'CYLTabBarController', '~> 1.6.1'
pod 'IQKeyboardManagerSwift', '~> 4.0.7'
pod 'AFNetworking', '~> 3.1.0'

use_frameworks!

