# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZhouDaoSwift' do

#Objective-C
pod 'CYLTabBarController', '~> 1.6.7'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'JSAnimatedImagesView', '~> 1.0.0'
#pod 'QiniuUpload', '~> 2.0.2'
#pod 'MBProgressHUD', '~> 1.0.0'
#pod 'pop', '~> 1.0.9'
#pod 'SDCycleScrollView', '~> 1.65'
#pod 'SDWebImage', '~> 3.8.2'

#Swift
#键盘
pod 'IQKeyboardManagerSwift', '~> 4.0.7'
#请求
pod 'Alamofire', '~> 4.2.0'
#解析json
pod 'SwiftyJSON', '~> 3.1.3'
#下拉刷新
pod 'NVActivityIndicatorView', '~> 3.0'
#加载图片
pod 'Kingfisher', '~> 3.2.1'
#一个iOS8风格的HUD,效果不错
pod 'PKHUD', '~> 4.0.0'
#加密解密,支持MD5,SHA,HMac,AES等
pod 'CryptoSwift', '~> 0.6.6'

end

#target 'ZhouDaoSwiftTests' do
#
#end

#target 'ZhouDaoSwiftUITests' do
#
#end


