# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :osx, '10.10'

target '12306ForMac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'XCGLogger', '~> 4.0.0'
pod 'Alamofire', '~> 4.2.0'
pod 'PromiseKit', '~> 4.0.5'
  # Pods for 12306ForMac

end
